setwd ("/home/ashleyhawkins/Documents/TEF data/TFKPAP1/Path 2011 remeasure join/math")

bc1math<-read.csv("bc1math.csv", quote="", header=T)
bc2math<-read.csv("bc2math.csv", quote="", header=T)
bc3math<-read.csv("bc3math.csv", quote="", header=T)
bn1math<-read.csv("bn1math.csv", quote="", header=T)
bn2math<-read.csv("bn2math.csv", quote="", header=T)
bn3math<-read.csv("bn3math.csv", quote="", header=T)
bs1math<-read.csv("bs1math.csv", quote="", header=T)
bs2math<-read.csv("bs2math.csv", quote="", header=T)
bs3math<-read.csv("bs3math.csv", quote="", header=T)
uc1math<-read.csv("uc1math.csv", quote="", header=T)
uc2math<-read.csv("uc2math.csv", quote="", header=T)
uc3math<-read.csv("uc3math.csv", quote="", header=T)
un1math<-read.csv("un1math.csv", quote="", header=T)
un2math<-read.csv("un2math.csv", quote="", header=T)
un3math<-read.csv("un3math.csv", quote="", header=T)
us1math<-read.csv("us1math.csv", quote="", header=T)
us2math<-read.csv("us2math.csv", quote="", header=T)
us3math<-read.csv("us3math.csv", quote="", header=T)

install.packages("gtools")

smartbind(bc1math, bc2math)
library(plyr)
tmp<-rbind.fill(bc1math,bc2math,bc3math,bn1math,bn2math,bn3math,bs1math,bs2math,bs3math,uc1math,uc2math,uc3math,un1math,un2math,un3math,us1math,us2math,us3math)

write.table (tmp, "/home/ashleyhawkins/Documents/TEF data/TFKPAP1/Path 2011 remeasure join/math/tmp.csv", quote=F, sep=",", row.names=FALSE)

list.files("/home/ashleyhawkins/Documents/TEF data/TFKPAP1/Path 2011 remeasure join/math")

bc1mathcomcol<-names(bc1math)
bc2mathcomcol<-names(bc2math)
bc3mathcomcol<-names(bc3math)
bn1mathcomcol<-names(bn1math)
bn2mathcomcol<-names(bn2math)
bn3mathcomcol<-names(bn3math)
bs1mathcomcol<-names(bs1math)
bs2mathcomcol<-names(bs2math)
bs3mathcomcol<-names(bs3math)
uc1mathcomcol<-names(uc1math)
uc2mathcomcol<-names(uc2math)
uc3mathcomcol<-names(uc3math)
un1mathcomcol<-names(un1math)
un2mathcomcol<-names(un2math)
un3mathcomcol<-names(un3math)
us1mathcomcol<-names(us1math)
us2mathcomcol<-names(us2math)
us3mathcomcol<-names(us3math)
